### PR TITLE
Remove dependency on GLIBCXX_3.4.21

### PR DESCRIPTION
**Pull request by vildhet**
This will allow to use the module with older libstd.so

### CODE REVIEW

**Comment by jduncanator** [comment]
The cflags property needs to be set to c++11 in order for the module to correctly work on older node.js versions under Mac OS X.

From my understanding it should be as simple as adding the `c++11` flag back to the `cflags` property instead of the `cflags_cc` property.

**Comment by vildhet** [comment]
Ok, I've set flags back to the `cflags` property. The `D_GLIBCXX_USE_CXX11_ABI` works in this case too.

**Comment by jduncanator** [comment]
I'll spend some time testing this today, and merge if good!

**Comment by vildhet** [comment]
Hi, any news on that?

**Comment by jduncanator** [comment]
I've tested and merged the changes.

**Comment by jduncanator** [comment]
@vildhet These changes are now available in the latest version of node-diskusage

**Comment by vildhet** [comment]
Thanks!

**Pull request merged**
