### PR TITLE
Update to latest ffi and ref packages.

### PR DESCRIPTION
**Pull request by weiyin**
This adds support for node.js v0.12.x and io.js >= v1.1.0.

### CODE REVIEW

**Comment by jduncanator** [comment]
Thanks!

**Comment by weiyin** [comment]
Yours is the only decent package that uses native bindings instead of calling "df". Would you mind pushing out a new version to npm?

**Comment by jduncanator** [comment]
I'll push the changes now.

**Comment by weiyin** [comment]
Thanks so much!

**Comment by jduncanator** [comment]
Done.

**Pull request merged**
