### PR TITLE
Re-implement in C++ with just NaN dependency

### PR DESCRIPTION
**Pull request by miniak**
Fixes https://github.com/jduncanator/node-diskusage/issues/14

### CODE REVIEW

**Comment by miniak** [comment]
I would also like to replace GetDiskFreeSpaceExA with GetDiskFreeSpaceExW to make it more robust.

**Comment by jduncanator** [comment]
Looks good. Go ahead and change the GetDiskFreeSpaceExA call to GetDiskFreeSpaceExW. The only reason I was using the ANSI version was an incompatibility with FFI when I initially wrote the library.

**Comment by miniak** [comment]
I'll try to get to that tomorrow. Or over the weekend.

**Comment by miniak** [comment]
I have posted an update version:
- I have refactored the code a bit, I think it's cleaner now
- added a `checkSync` version returning the result or throwing an Error()
- added embedded TypeScript .d.ts file

TODO:
- update README.md to document the new `checkSync` function
- replace `GetDiskFreeSpaceExA` with `GetDiskFreeSpaceExW`

**Comment by miniak** [comment]
@jduncanator can you please review the current version before I continue with the rest of the TODOs? Thanks

**Comment by jduncanator** [comment]
LGTM

**Comment by miniak** [comment]
@jduncanator I've resolved the first two TODO items.

**Comment by jduncanator** [comment]
Thanks @miniak. Great work. Will run some tests on all three platforms and will merge if everything looks good.

**Comment by miniak** [comment]
@jduncanator, one last update. I've found `Nan::ErrnoException()`, which can be used to generate errors similar to what you get from native `fs` module. This resolves https://github.com/jduncanator/node-diskusage/issues/13.

https://github.com/nodejs/nan/blob/master/doc/errors.md#api_nan_errno_exception
https://nodejs.org/api/errors.html#errors_class_system_error

**Comment by jduncanator** [comment]
Looks all good to me. I've tested it briefly on Windows, Mac and Linux and all three seem to be reporting the correct values. Will go ahead and merge the changes. Thanks for your contributions! It's much appreciated.

**Pull request merged**
