### PR TITLE
Only try/catch native call not callback

### PR DESCRIPTION
**Pull request by braydonf**

### CODE REVIEW

**Comment by jduncanator** [comment]
Hey @braydonf , thanks for the PR.

I've consciously avoided using ES6 features in the past to maintain backwards compatibility with older versions of Node. This library aims to support back to 0.12.x, as a lot of users using this library are running in production with this version of Node.

You're more than welcome to update the PR to remove the ES6 features, but at that point it seems like the majority of the reasoning behind the PR would have been lost.

I've also noticed that some of the changes would be breaking. The current API passes in `undefined` as either the error or result values, and changing these to `null` would be a breaking change in the event user code is doing something along the lines of the following: `if(result == undefined)`. I'd prefer to avoid such a trivial change requiring a new major version of the library.

Let me know your thoughts on the above.

**Comment by jduncanator** [comment]
Ah, after taking a second read of your PR title, and a look at the PR itself, I now see what you were trying to get at. My apologies. 

If you want to resubmit a PR without the ES6 features and the breaking changes, I'd be happy to merge!

**Comment by braydonf** [comment]
Okay, updated.

**Comment by jduncanator** [comment]
Cheers!

**Comment by braydonf** [comment]
Thanks!

**Pull request merged**
